# Generated by Django 3.2 on 2022-04-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otptoken',
            options={'ordering': ['-expiry_time'], 'verbose_name': 'OTPToken', 'verbose_name_plural': 'OTPTokens'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
