# Generated by Django 3.2 on 2022-05-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_status'),
        ('accountProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(related_name='account_tags', to='blog.Tag'),
        ),
    ]
