# Generated by Django 3.2 on 2022-04-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220420_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Heading'),
        ),
    ]
