# Generated by Django 3.2 on 2022-04-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220427_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
